SinpeEmpresarial/SinpeEmpresarial.Web/Controllers/CajaController.cs
using SinpeEmpresarial.Application.Dtos.Caja;
using SinpeEmpresarial.Application.Interfaces;
using SinpeEmpresarial.Application.Services;
using System;
using System.Linq;
using System.Web.Mvc;

[Authorize(Roles = "Cajero, Administrador")]
public class CajaController : Controller
{
    private readonly ICajaService _cajaService;
    private readonly ISinpeService _sinpeService;
    private readonly IComercioService _comercioService;

    public CajaController(ICajaService cajaService, ISinpeService sinpeService, IComercioService comercioService)
    {
        _cajaService = cajaService;
        _sinpeService = sinpeService;
        _comercioService = comercioService;
    }

    public ActionResult Index()
    {
        var allCajas = _cajaService.GetAll();
        return View(allCajas);
    }

    public ActionResult PorComercio(int comercioId)
    {
        var cajas = _cajaService.GetCajasByComercio(comercioId);
        return View("Index", cajas);
    }

    public ActionResult Create()
    {
        var comercios = _comercioService.GetAllComercios();
        ViewBag.Comercios = new SelectList(comercios, "IdComercio", "Nombre");
        return View();
    }

    [Authorize(Roles = "Administrador")]
    [HttpPost]
    public ActionResult Create(CreateCajaDto dto)
    {
        _cajaService.AddCaja(dto);
        return RedirectToAction("PorComercio", new { comercioId = dto.IdComercio });
    }

    public ActionResult Edit(int id)
    {
        var caja = _cajaService.GetById(id);
        return View(new EditCajaDto
        {
            IdCaja = caja.IdCaja,
            Nombre = caja.Nombre,
            Descripcion = caja.Descripcion,
            TelefonoSINPE = caja.TelefonoSINPE,
            Estado = caja.Estado
        });
    }
    [Authorize(Roles = "Administrador")]
    [HttpPost]
    public ActionResult Edit(EditCajaDto dto)
    {
        _cajaService.EditCaja(dto);
        return RedirectToAction("Index");
    }

    public ActionResult VerSinpe(string telefonoSINPE)
    {
        var sinpes = _sinpeService.GetByCajaTelefono(telefonoSINPE);

        // Debug step: see how many were returned
        ViewBag.DebugCount = sinpes.Count;
        ViewBag.Tel = telefonoSINPE;

        return View(sinpes);
    }
    [HttpPost]
    public ActionResult Sincronizar(int id, string telefonoDestino)
    {
        _sinpeService.Sincronizar(id);
        return RedirectToAction("VerSinpe", new { telefonoSINPE = telefonoDestino });
    }
}

SinpeEmpresarial/SinpeEmpresarial.Web/Controllers/ComercioController.cs
using SinpeEmpresarial.Application.Dtos;
using SinpeEmpresarial.Application.Interfaces;
using SinpeEmpresarial.Web.Filters;
using System;
using System.Web.Mvc;

namespace SinpeEmpresarial.Web.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ComercioController : Controller
    {
        private readonly IComercioService _comercioService;

        private void LlenarViewBags(int? tipoDeComercioSeleccionado = null)
        {
            ViewBag.TipoIdentificacion = new SelectList(
                new[]
                {
                    new { Value = 1, Text = "Física" },
                    new { Value = 2, Text = "Jurídica" }
                },
                "Value", "Text"
            );

            ViewBag.TipoDeComercio = new SelectList(
                new[]
                {
                    new { Value = 1, Text = "Restaurantes" },
                    new { Value = 2, Text = "Supermercados" },
                    new { Value = 3, Text = "Ferreterías" },
                    new { Value = 4, Text = "Otros" }
                },
                "Value", "Text", tipoDeComercioSeleccionado
            );
        }

        public ComercioController(IComercioService comercioService)
        {
            _comercioService = comercioService;
        }

        // GET: Comercio
        public ActionResult Index()
        {
            var comercios = _comercioService.GetAllComercios();
            return View(comercios);
        }

        // GET: Comercio/Details/5
        public ActionResult Details(int id)
        {
            var comercio = _comercioService.GetComercioById(id);
            if (comercio == null)
                return HttpNotFound();
            return View(comercio);
        }

        // GET: Comercio/Create
        public ActionResult Create()
        {
            LlenarViewBags();
            return View();
        }

        // POST: Comercio/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ComercioCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                LlenarViewBags();
                return View(dto);
            }
            _comercioService.RegisterComercio(dto);
            return RedirectToAction("Index");
        }

        // GET: Comercio/Edit/5
        public ActionResult Edit(int id)
        {
            var comercio = _comercioService.GetComercioById(id);
            if (comercio == null)
                return HttpNotFound();

            var editDto = new ComercioEditDto
            {
                IdComercio = id,
                Nombre = comercio.Nombre,
                TipoDeComercio = comercio.TipoDeComercio,
                Telefono = comercio.Telefono,
                CorreoElectronico = comercio.CorreoElectronico,
                Direccion = comercio.Direccion,
                Estado = comercio.Estado
            };
            LlenarViewBags(editDto.TipoDeComercio);
            return View(editDto);
        }

        // POST: Comercio/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ComercioEditDto editDto)
        {
            if (!ModelState.IsValid)
            {
                LlenarViewBags(editDto.TipoDeComercio);
                return View(editDto);
            }

            _comercioService.EditComercio(editDto);
            return RedirectToAction("Index");
        }
    }
}

SinpeEmpresarial/SinpeEmpresarial.Web/Controllers/ConfiguracionComercioController.cs
using SinpeEmpresarial.Application.Dtos.ConfiguracionComercio;
using SinpeEmpresarial.Application.Interfaces;
using System;
using System.Web.Mvc;

namespace SinpeEmpresarial.Web.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ConfiguracionComercioController : Controller
    {

        private readonly IConfiguracionComercioService _configuracioncomercioService;
        private readonly IComercioService _comercioService;

        private void LlenarViewBags(int? tipoDeCofiguracionSeleccionado = null)
        {
            ViewBag.TipoConfiguracion = new SelectList(
                new[]
                {
                    new { Value = 1, Text = "Plataforma" },
                    new { Value = 2, Text = "Externa" },
                    new { Value = 3, Text = "Ambas" }
                },
                "Value", "Text"
            );
        }

        public ConfiguracionComercioController(IConfiguracionComercioService configuracioncomercioService, IComercioService comercioService)
        {
            _configuracioncomercioService = configuracioncomercioService;
            _comercioService = comercioService;
        }

        // GET: Configuracion Comercio
        public ActionResult Index()
        {
            var configuraciones = _configuracioncomercioService.GetAllConfiguraciones();
            return View(configuraciones);
        }

        // GET: Configuracion Comercio/Details/5
        public ActionResult Details(int id)
        {
            var configuracion = _configuracioncomercioService.GetConfiguracionById(id);
            if (configuracion == null)
                return HttpNotFound();
            return View(configuracion);
        }

        // GET: Configuracion Comercio/Create
        public ActionResult Create(int idComercio)
        {
            var model = new ConfiguracionComercioCreateDto { IdComercio = idComercio };
            var comercio = _comercioService.GetComercioById(idComercio);
            ViewBag.NombreComercio = comercio.Nombre;
            LlenarViewBags();
            return View(model);
        }

        // POST: Configuracion Comercio/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ConfiguracionComercioCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                LlenarViewBags();
                return View(dto);
            }

            _configuracioncomercioService.RegisterConfiguracionComercio(dto);
            return RedirectToAction("Index");
        }
        // GET: ConfiguracionComercio/Edit
        public ActionResult Edit(int idComercio)
        {
            var configuracion = _configuracioncomercioService.GetConfiguracionByComercio(idComercio);
            if (configuracion == null)
                return HttpNotFound();

            var comercio = _comercioService.GetComercioById(idComercio);

            var editDto = new ConfiguracionComercioEditDto
            { 
                IdConfiguracion = configuracion.IdConfiguracion,
                IdComercio = idComercio,
                TipoConfiguracion = configuracion.TipoConfiguracion,
                Comision = configuracion.Comision,
                Estado = configuracion.Estado
            };
            ViewBag.NombreComercio = comercio.Nombre;
            LlenarViewBags(editDto.TipoConfiguracion);
            return View(editDto);
        }

        // POST: ConfiguracionComercio/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ConfiguracionComercioEditDto editDto)
        {
            if (!ModelState.IsValid)
            {
                LlenarViewBags(editDto.TipoConfiguracion);
                return View(editDto);
            }
            _configuracioncomercioService.EditConfiguracionComercio(editDto);
            return RedirectToAction("Index");
        }
    }
}

SinpeEmpresarial/SinpeEmpresarial.Web/Views/Comercio/Create.cshtml
@model SinpeEmpresarial.Application.Dtos.ComercioCreateDto
 
@{
    ViewBag.Title = "Registrar Comercio";
}

<h2>Registrar Comercio</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Identificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoIdentificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoIdentificacion, (SelectList)ViewBag.TipoIdentificacion, "-- Seleccione un tipo --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoIdentificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoDeComercio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoDeComercio, (SelectList)ViewBag.TipoDeComercio, "-- Seleccione un tipo --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoDeComercio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-primary" />

                @Html.ActionLink("Volver a la lista", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinpeEmpresarial/SinpeEmpresarial.Web/Views/Comercio/Details.cshtml
@model SinpeEmpresarial.Application.Dtos.ComercioDetailDto

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Identificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoIdentificacionString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoIdentificacionString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDeComercioString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDeComercioString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoString)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdComercio }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</p>

SinpeEmpresarial/SinpeEmpresarial.Web/Views/Comercio/Edit.cshtml
@model SinpeEmpresarial.Application.Dtos.ComercioEditDto

@{
    ViewBag.Title = "Editar Comercio";
}

<h2>Editar Comercio</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdComercio)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TipoDeComercio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TipoDeComercio, (SelectList)ViewBag.TipoDeComercio, "-- Seleccione un tipo --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TipoDeComercio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Estado)
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <br/>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary" />
            @Html.ActionLink("Volver a la lista", "Index", "Comercio", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinpeEmpresarial/SinpeEmpresarial.Web/Views/Comercio/Index.cshtml
@model IEnumerable<SinpeEmpresarial.Application.Dtos.ComercioListDto>

@{
    ViewBag.Title = "Comercios";
}

<style>
    .table-striped tbody tr:nth-of-type(odd) { background-color: #f8f9fa; }
    .table th { background-color: #e9ecef; font-weight: 600; border-right: 1px solid #dee2e6; }
    .table td { border-right: 1px solid #dee2e6; }
    .badge-success { background-color: #28a745; color: white; }
    .badge-secondary { background-color: #6c757d; color: white; }
</style>

<h2>Comercios Registrados</h2>

<p>
    @Html.ActionLink("Registrar Comercio", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Ver todas las configuraciones", "Index", "ConfiguracionComercio", null, new { @class = "btn btn-info"})

</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Tipo de ID</th>
            <th>Nombre</th>
            <th>Tipo de Comercio</th>
            <th>Telefono</th>
            <th>Correo</th>
            <th>Estado</th>
            <th>Acciones</th>
            <th>Configuración</th>
        </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Identificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoIdentificacionString)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoDeComercioString)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstadoString)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdComercio }, new { @class = "btn btn-sm btn-warning" })
                @Html.ActionLink("Detalles", "Details", new { id = item.IdComercio }, new { @class = "btn btn-sm btn-secondary" })
                @Html.ActionLink("Ver Cajas", "PorComercio", "Caja", new { comercioId = item.IdComercio }, new { @class = "btn btn-sm btn-info" })
            </td>
            <td>
                @if (item.TieneConfiguracion)
                {
                    @Html.ActionLink("Editar Configuración", "Edit", "ConfiguracionComercio", new { idComercio = item.IdComercio}, new { @class = "btn btn-sm btn-success" })
                }
                else
                {
                    @Html.ActionLink("Registrar Configuración", "Create", "ConfiguracionComercio", new { idComercio = item.IdComercio}, new { @class = "btn btn-sm btn-primary" })
                }
            </td>
        </tr>
    }

</table>